### ISSUE TITLE
gtk3 >= 3.22 support

### ISSUE THREAD

**Issue by awissu** [mirkobrombin/Bottles#24]
Hi!
When I try to run app on openSUSE Tumbleweed I get the following message:
```
Traceback (most recent call last):
  File "/usr/bin/com.github.mirkobrombin.bottles", line 28, in <module>
    import main
  File "/usr/share/com.github.mirkobrombin.bottles/bottles/main.py", line 96, in <module>
    Gtk.STYLE_PROVIDER_PRIORITY_APPLICATION
TypeError: Argument 0 does not allow None as a value
```

**Comment by mirkobrombin** [comment]
Which python version are you using?

**Comment by awissu** [comment]
Python 3.6.4

**Comment by mirkobrombin** [comment]
Can you try with 2.7?

**Comment by awissu** [comment]
```
Traceback (most recent call last):
  File "/usr/bin/com.github.mirkobrombin.bottles", line 28, in <module>
    import main
  File "/usr/share/com.github.mirkobrombin.bottles/bottles/main.py", line 30, in <module>
    import constants as cn
  File "/usr/share/com.github.mirkobrombin.bottles/bottles/constants.py", line 32, in <module>
    except FileNotFoundError:
NameError: name 'FileNotFoundError' is not defined
```

**Comment by mirkobrombin** [comment]
I need to debug the application on opensuse

**Comment by mirkobrombin** [comment]
Bug confirmed
